name: Textlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: ./node_modules/.bin/textlint *.md --fix
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '[ci skip] Automatic textlint fixes'
        branch: 'master'
        file_pattern: './\*.md'
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
      if: github.repository == 'bobby285271/textlint-demo'

